version: 0.2
phases:
  install:
    runtime-version:
      nodejs: 12
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building project..."
      - npm run build
      - npm run export
  post_build:
    commands:
      - echo 'Updating files in S3 bucket...'
      - aws s3 sync .out/ s3://blog-app-2021 --delete
